/// Flutter icons FigmaIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FigmaIcons
///      fonts:
///       - asset: assets/icons/FigmaIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FigmaIcons {
  const FigmaIcons();

  static const _kFontFam = 'FigmaIcons';
  static const String? _kFontPkg = null;

  static const IconData calendar = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
